---
title: "Trabalho - Parte I"
author: "Caio, Taiguara e Walmir"
date: "10/30/2019"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(encoding = 'UTF-8')
```

## Parametros

```{r params}
n = 500

## Parametros reais da distribuicao amostral 
mu = 13
sigma2 = 0.25
nu = 0.4

#Parametros das distribuicoes a priori
m = 12
V = 1
a = 4
d = 1
```

## Gerando a amostra

Gerando uma amostra de tamanho $n$:

```{r sample, echo=TRUE}
U = sample(c(1,100), n, replace = T, c(1-nu,nu))
sample = rnorm(n, mu, sqrt(sigma2*U))
hist(sample, breaks = 50, prob=T)
```

## Definindo *a posteriori*

```{r log_likelihood, echo=TRUE}
logA <- function(X, mu, sigma2, nu) {
  n = length(X)
  termo100 = log(nu/10) -(X-mu)^2/(2*100*sigma2)
  termo1 = log(1 - nu) -(X-mu)^2/(2*sigma2)
  
  indicator = (termo100 > termo1)
  
  # log1p(x) computes log(1+x) accurately also for |x| << 1.
  log_caso100 = termo100 + log1p( (10*(1-nu)/nu) * exp( (-(X-mu)^2/(2*sigma2)) - (-(X-mu)^2/(2*100*sigma2)) ) ) 
  log_caso100[!indicator] = 0
  log_caso1   =   termo1 + log1p( nu/(10*(1-nu)) * exp( (-(X-mu)^2/(2*100*sigma2)) - (-(X-mu)^2/(2*sigma2)) ) ) 
  log_caso1[indicator] = 0

  sum(log_caso100)+sum(log_caso1)
}

logh <- function(aux, n, mu, sigma2, nu, m, V, a, d) {
  aux + ((n+1)/2 + a + 1)*log(1/sigma2) + (-((mu-m)^2/(2*V) + d) / sigma2)
}

```



# Quadratura

## Definindo as regioes de aproximacao

```{r inf_params, echo=TRUE}
L = 100

mu_bounds = 3
mu_step = 2*mu_bounds/L
mu_grid = seq(m-mu_bounds, m+mu_bounds, mu_step)

sigma2_step = (sigma2*2)/L
sigma2_grid = seq(0.1, sigma2*2, sigma2_step)

nu_step = 1/L
nu_grid = seq(0.2, 0.6, nu_step)
```


## Estimando o K

```{r k, echo=TRUE}

inv_k = 0
n = length(sample)

for (i in 1:length(mu_grid)) {
  for (j in 1:length(sigma2_grid)) {
    for (k in 1:length(nu_grid)) {
      aux = logA(sample, mu_grid[i], sigma2_grid[j], nu_grid[k])
      print(aux)
      logh_ijk = logh(aux, n, mu_grid[i], sigma2_grid[j], nu_grid[k], m, V, a, d)
      print(logh_ijk)
      inv_k = inv_k + exp(logh_ijk)
      print(inv_k)
    }
  }
}

inv_k = inv_k * nu_step * sigma2_step * mu_step

k = 1/inv_k
```





